### ISSUE TITLE
Rule to block pods with containers without limits

### ISSUE THREAD

**Issue by palmerabollo** [HotelsDotCom/kube-graffiti#3]
I wonder whether it is possible to write a field-selector that tries to match elements in an array. The use case would be to block pods that have containers (spec.template.spec.containers) without resources/limits or resources/requests.

This is what I tried, but I guess the expression `not spec.template.spec.containers.[].resources` is not valid as a `field-selector` Am I right?

```
    - registration:
        name: block-pods-without-requests-and-limits
        targets:
        - api-groups:
          - "*"
          api-versions:
          - v1
          resources:
          - pod
        failure-policy: Ignore
      matchers:
        field-selectors:
          - not spec.template.spec.containers.[].resources
      payload:
        block: true
```

Thank you.
